# Generated by Django 3.0 on 2019-12-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
